//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace InterviewTest.HotelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.design.americaneagle.com", ConfigurationName="HotelService.HotelsSoap")]
    public interface HotelsSoap {
        
        // CODEGEN: Generating message contract since message GetHotelRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.design.americaneagle.com/GetHotel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InterviewTest.HotelService.GetHotelResponse GetHotel(InterviewTest.HotelService.GetHotelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.design.americaneagle.com/GetHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<InterviewTest.HotelService.GetHotelResponse> GetHotelAsync(InterviewTest.HotelService.GetHotelRequest request);
        
        // CODEGEN: Generating message contract since message GetHotelsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.design.americaneagle.com/GetHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InterviewTest.HotelService.GetHotelsResponse GetHotels(InterviewTest.HotelService.GetHotelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.design.americaneagle.com/GetHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<InterviewTest.HotelService.GetHotelsResponse> GetHotelsAsync(InterviewTest.HotelService.GetHotelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.design.americaneagle.com/SiteScope", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SiteScope();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.design.americaneagle.com/SiteScope", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SiteScopeAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class HotelCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class HotelPagingOptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HotelSortField sortFieldField;
        
        private bool sortAscendingField;
        
        private int pageSizeField;
        
        private int pageNumberField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HotelSortField sortField {
            get {
                return this.sortFieldField;
            }
            set {
                this.sortFieldField = value;
                this.RaisePropertyChanged("sortField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool sortAscending {
            get {
                return this.sortAscendingField;
            }
            set {
                this.sortAscendingField = value;
                this.RaisePropertyChanged("sortAscending");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
                this.RaisePropertyChanged("pageNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public enum HotelSortField {
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        StateProvince,
        
        /// <remarks/>
        PostalCode,
        
        /// <remarks/>
        Distance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class CityFilterCity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class MultipleCityFilterCity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostalCodeFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CityFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NameFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExcludeHotelsFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipleCityFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostalCodeRangeFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MerchantOnlyFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateProvinceFilter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public abstract partial class HotelFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class PostalCodeFilter : HotelFilter {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class CountryFilter : HotelFilter {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class CityFilter : HotelFilter {
        
        private CityFilterCity valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CityFilterCity value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class NameFilter : HotelFilter {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class ExcludeHotelsFilter : HotelFilter {
        
        private int[] idsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public int[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
                this.RaisePropertyChanged("ids");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class MultipleCityFilter : HotelFilter {
        
        private MultipleCityFilterCity[] citiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MultipleCityFilterCity[] cities {
            get {
                return this.citiesField;
            }
            set {
                this.citiesField = value;
                this.RaisePropertyChanged("cities");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class PostalCodeRangeFilter : HotelFilter {
        
        private string postalCodeField;
        
        private int rangeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class MerchantOnlyFilter : HotelFilter {
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class StateProvinceFilter : HotelFilter {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class FilterContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HotelFilter[] filtersField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public HotelFilter[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
                this.RaisePropertyChanged("filters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class ImageOptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool includeImagesField;
        
        private int maxWidthField;
        
        private int maxHeightField;
        
        private int maxThumbnailWidthField;
        
        private int maxThumbnailHeightField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool includeImages {
            get {
                return this.includeImagesField;
            }
            set {
                this.includeImagesField = value;
                this.RaisePropertyChanged("includeImages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int maxWidth {
            get {
                return this.maxWidthField;
            }
            set {
                this.maxWidthField = value;
                this.RaisePropertyChanged("maxWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int maxHeight {
            get {
                return this.maxHeightField;
            }
            set {
                this.maxHeightField = value;
                this.RaisePropertyChanged("maxHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int maxThumbnailWidth {
            get {
                return this.maxThumbnailWidthField;
            }
            set {
                this.maxThumbnailWidthField = value;
                this.RaisePropertyChanged("maxThumbnailWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int maxThumbnailHeight {
            get {
                return this.maxThumbnailHeightField;
            }
            set {
                this.maxThumbnailHeightField = value;
                this.RaisePropertyChanged("maxThumbnailHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class HotelImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string captionField;
        
        private string uRLField;
        
        private int widthField;
        
        private int heightField;
        
        private string thumbnailURLField;
        
        private int thumbnailHeightField;
        
        private int thumbnailWidthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
                this.RaisePropertyChanged("Caption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ThumbnailURL {
            get {
                return this.thumbnailURLField;
            }
            set {
                this.thumbnailURLField = value;
                this.RaisePropertyChanged("ThumbnailURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ThumbnailHeight {
            get {
                return this.thumbnailHeightField;
            }
            set {
                this.thumbnailHeightField = value;
                this.RaisePropertyChanged("ThumbnailHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ThumbnailWidth {
            get {
                return this.thumbnailWidthField;
            }
            set {
                this.thumbnailWidthField = value;
                this.RaisePropertyChanged("ThumbnailWidth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.design.americaneagle.com")]
    public partial class Hotel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double distanceField;
        
        private string bookingLinkField;
        
        private HotelImage[] imagesField;
        
        private int hotelIDField;
        
        private string nameField;
        
        private string airportCodeField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string cityField;
        
        private string stateProvinceField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private double lowRateField;
        
        private double highRateField;
        
        private string marketingLevelField;
        
        private int confidenceField;
        
        private string hotelModifiedField;
        
        private string propertyTypeField;
        
        private string timeZoneField;
        
        private string gMTOffsetField;
        
        private string yearPropertyOpenedField;
        
        private string yearPropertyRenovatedField;
        
        private string nativeCurrencyField;
        
        private int numberOfRoomsField;
        
        private int numberOfSuitesField;
        
        private int numberOfFloorsField;
        
        private string checkInTimeField;
        
        private string checkOutTimeField;
        
        private bool hasValetParkingField;
        
        private bool hasContinentalBreakfastField;
        
        private bool hasInRoomMoviesField;
        
        private bool hasSaunaField;
        
        private bool hasWhirlpoolField;
        
        private bool hasVoiceMailField;
        
        private bool has24HourSecurityField;
        
        private bool hasParkingGarageField;
        
        private bool hasElectronicRoomKeysField;
        
        private bool hasCoffeeTeaMakerField;
        
        private bool hasSafeField;
        
        private bool hasVideoCheckOutField;
        
        private bool hasRestrictedAccessField;
        
        private bool hasInteriorRoomEntranceField;
        
        private bool hasExteriorRoomEntranceField;
        
        private bool hasCombinationField;
        
        private bool hasFitnessFacilityField;
        
        private bool hasGameRoomField;
        
        private bool hasTennisCourtField;
        
        private bool hasGolfCourseField;
        
        private bool hasInHouseDiningField;
        
        private bool hasInHouseBarField;
        
        private bool hasHandicapAccessibleField;
        
        private bool hasChildrenAllowedField;
        
        private bool hasPetsAllowedField;
        
        private bool hasTVInRoomField;
        
        private bool hasDataPortsField;
        
        private bool hasMeetingRoomsField;
        
        private bool hasBusinessCenterField;
        
        private bool hasDryCleaningField;
        
        private bool hasIndoorPoolField;
        
        private bool hasOutdoorPoolField;
        
        private bool hasNonSmokingRoomsField;
        
        private bool hasAirportTransportationField;
        
        private bool hasAirConditioningField;
        
        private bool hasClothingIronField;
        
        private bool hasWakeUpServiceField;
        
        private bool hasMiniBarInRoomField;
        
        private bool hasRoomServiceField;
        
        private bool hasHairDryerField;
        
        private bool hasCarRentDeskField;
        
        private bool hasFamilyRoomsField;
        
        private bool hasKitchenField;
        
        private bool hasMapField;
        
        private string propertyDescriptionField;
        
        private double ratingField;
        
        private string gDSChainCodeField;
        
        private string gDSChaincodeNameField;
        
        private string destinationIDField;
        
        private string drivingDirectionsField;
        
        private string nearbyAttractionsField;
        
        private bool aEIsMerchantField;
        
        private System.DateTime aEModifyDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BookingLink {
            get {
                return this.bookingLinkField;
            }
            set {
                this.bookingLinkField = value;
                this.RaisePropertyChanged("BookingLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public HotelImage[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
                this.RaisePropertyChanged("Images");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int HotelID {
            get {
                return this.hotelIDField;
            }
            set {
                this.hotelIDField = value;
                this.RaisePropertyChanged("HotelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AirportCode {
            get {
                return this.airportCodeField;
            }
            set {
                this.airportCodeField = value;
                this.RaisePropertyChanged("AirportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
                this.RaisePropertyChanged("Address3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
                this.RaisePropertyChanged("StateProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double LowRate {
            get {
                return this.lowRateField;
            }
            set {
                this.lowRateField = value;
                this.RaisePropertyChanged("LowRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double HighRate {
            get {
                return this.highRateField;
            }
            set {
                this.highRateField = value;
                this.RaisePropertyChanged("HighRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string MarketingLevel {
            get {
                return this.marketingLevelField;
            }
            set {
                this.marketingLevelField = value;
                this.RaisePropertyChanged("MarketingLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
                this.RaisePropertyChanged("Confidence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string HotelModified {
            get {
                return this.hotelModifiedField;
            }
            set {
                this.hotelModifiedField = value;
                this.RaisePropertyChanged("HotelModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PropertyType {
            get {
                return this.propertyTypeField;
            }
            set {
                this.propertyTypeField = value;
                this.RaisePropertyChanged("PropertyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("TimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string GMTOffset {
            get {
                return this.gMTOffsetField;
            }
            set {
                this.gMTOffsetField = value;
                this.RaisePropertyChanged("GMTOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string YearPropertyOpened {
            get {
                return this.yearPropertyOpenedField;
            }
            set {
                this.yearPropertyOpenedField = value;
                this.RaisePropertyChanged("YearPropertyOpened");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string YearPropertyRenovated {
            get {
                return this.yearPropertyRenovatedField;
            }
            set {
                this.yearPropertyRenovatedField = value;
                this.RaisePropertyChanged("YearPropertyRenovated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string NativeCurrency {
            get {
                return this.nativeCurrencyField;
            }
            set {
                this.nativeCurrencyField = value;
                this.RaisePropertyChanged("NativeCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int NumberOfRooms {
            get {
                return this.numberOfRoomsField;
            }
            set {
                this.numberOfRoomsField = value;
                this.RaisePropertyChanged("NumberOfRooms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int NumberOfSuites {
            get {
                return this.numberOfSuitesField;
            }
            set {
                this.numberOfSuitesField = value;
                this.RaisePropertyChanged("NumberOfSuites");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int NumberOfFloors {
            get {
                return this.numberOfFloorsField;
            }
            set {
                this.numberOfFloorsField = value;
                this.RaisePropertyChanged("NumberOfFloors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string CheckInTime {
            get {
                return this.checkInTimeField;
            }
            set {
                this.checkInTimeField = value;
                this.RaisePropertyChanged("CheckInTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CheckOutTime {
            get {
                return this.checkOutTimeField;
            }
            set {
                this.checkOutTimeField = value;
                this.RaisePropertyChanged("CheckOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool HasValetParking {
            get {
                return this.hasValetParkingField;
            }
            set {
                this.hasValetParkingField = value;
                this.RaisePropertyChanged("HasValetParking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public bool HasContinentalBreakfast {
            get {
                return this.hasContinentalBreakfastField;
            }
            set {
                this.hasContinentalBreakfastField = value;
                this.RaisePropertyChanged("HasContinentalBreakfast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public bool HasInRoomMovies {
            get {
                return this.hasInRoomMoviesField;
            }
            set {
                this.hasInRoomMoviesField = value;
                this.RaisePropertyChanged("HasInRoomMovies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool HasSauna {
            get {
                return this.hasSaunaField;
            }
            set {
                this.hasSaunaField = value;
                this.RaisePropertyChanged("HasSauna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public bool HasWhirlpool {
            get {
                return this.hasWhirlpoolField;
            }
            set {
                this.hasWhirlpoolField = value;
                this.RaisePropertyChanged("HasWhirlpool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public bool HasVoiceMail {
            get {
                return this.hasVoiceMailField;
            }
            set {
                this.hasVoiceMailField = value;
                this.RaisePropertyChanged("HasVoiceMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public bool Has24HourSecurity {
            get {
                return this.has24HourSecurityField;
            }
            set {
                this.has24HourSecurityField = value;
                this.RaisePropertyChanged("Has24HourSecurity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public bool HasParkingGarage {
            get {
                return this.hasParkingGarageField;
            }
            set {
                this.hasParkingGarageField = value;
                this.RaisePropertyChanged("HasParkingGarage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public bool HasElectronicRoomKeys {
            get {
                return this.hasElectronicRoomKeysField;
            }
            set {
                this.hasElectronicRoomKeysField = value;
                this.RaisePropertyChanged("HasElectronicRoomKeys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public bool HasCoffeeTeaMaker {
            get {
                return this.hasCoffeeTeaMakerField;
            }
            set {
                this.hasCoffeeTeaMakerField = value;
                this.RaisePropertyChanged("HasCoffeeTeaMaker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public bool HasSafe {
            get {
                return this.hasSafeField;
            }
            set {
                this.hasSafeField = value;
                this.RaisePropertyChanged("HasSafe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public bool HasVideoCheckOut {
            get {
                return this.hasVideoCheckOutField;
            }
            set {
                this.hasVideoCheckOutField = value;
                this.RaisePropertyChanged("HasVideoCheckOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public bool HasRestrictedAccess {
            get {
                return this.hasRestrictedAccessField;
            }
            set {
                this.hasRestrictedAccessField = value;
                this.RaisePropertyChanged("HasRestrictedAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public bool HasInteriorRoomEntrance {
            get {
                return this.hasInteriorRoomEntranceField;
            }
            set {
                this.hasInteriorRoomEntranceField = value;
                this.RaisePropertyChanged("HasInteriorRoomEntrance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public bool HasExteriorRoomEntrance {
            get {
                return this.hasExteriorRoomEntranceField;
            }
            set {
                this.hasExteriorRoomEntranceField = value;
                this.RaisePropertyChanged("HasExteriorRoomEntrance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public bool HasCombination {
            get {
                return this.hasCombinationField;
            }
            set {
                this.hasCombinationField = value;
                this.RaisePropertyChanged("HasCombination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public bool HasFitnessFacility {
            get {
                return this.hasFitnessFacilityField;
            }
            set {
                this.hasFitnessFacilityField = value;
                this.RaisePropertyChanged("HasFitnessFacility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public bool HasGameRoom {
            get {
                return this.hasGameRoomField;
            }
            set {
                this.hasGameRoomField = value;
                this.RaisePropertyChanged("HasGameRoom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public bool HasTennisCourt {
            get {
                return this.hasTennisCourtField;
            }
            set {
                this.hasTennisCourtField = value;
                this.RaisePropertyChanged("HasTennisCourt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public bool HasGolfCourse {
            get {
                return this.hasGolfCourseField;
            }
            set {
                this.hasGolfCourseField = value;
                this.RaisePropertyChanged("HasGolfCourse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public bool HasInHouseDining {
            get {
                return this.hasInHouseDiningField;
            }
            set {
                this.hasInHouseDiningField = value;
                this.RaisePropertyChanged("HasInHouseDining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public bool HasInHouseBar {
            get {
                return this.hasInHouseBarField;
            }
            set {
                this.hasInHouseBarField = value;
                this.RaisePropertyChanged("HasInHouseBar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public bool HasHandicapAccessible {
            get {
                return this.hasHandicapAccessibleField;
            }
            set {
                this.hasHandicapAccessibleField = value;
                this.RaisePropertyChanged("HasHandicapAccessible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public bool HasChildrenAllowed {
            get {
                return this.hasChildrenAllowedField;
            }
            set {
                this.hasChildrenAllowedField = value;
                this.RaisePropertyChanged("HasChildrenAllowed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public bool HasPetsAllowed {
            get {
                return this.hasPetsAllowedField;
            }
            set {
                this.hasPetsAllowedField = value;
                this.RaisePropertyChanged("HasPetsAllowed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public bool HasTVInRoom {
            get {
                return this.hasTVInRoomField;
            }
            set {
                this.hasTVInRoomField = value;
                this.RaisePropertyChanged("HasTVInRoom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public bool HasDataPorts {
            get {
                return this.hasDataPortsField;
            }
            set {
                this.hasDataPortsField = value;
                this.RaisePropertyChanged("HasDataPorts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public bool HasMeetingRooms {
            get {
                return this.hasMeetingRoomsField;
            }
            set {
                this.hasMeetingRoomsField = value;
                this.RaisePropertyChanged("HasMeetingRooms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public bool HasBusinessCenter {
            get {
                return this.hasBusinessCenterField;
            }
            set {
                this.hasBusinessCenterField = value;
                this.RaisePropertyChanged("HasBusinessCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public bool HasDryCleaning {
            get {
                return this.hasDryCleaningField;
            }
            set {
                this.hasDryCleaningField = value;
                this.RaisePropertyChanged("HasDryCleaning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public bool HasIndoorPool {
            get {
                return this.hasIndoorPoolField;
            }
            set {
                this.hasIndoorPoolField = value;
                this.RaisePropertyChanged("HasIndoorPool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public bool HasOutdoorPool {
            get {
                return this.hasOutdoorPoolField;
            }
            set {
                this.hasOutdoorPoolField = value;
                this.RaisePropertyChanged("HasOutdoorPool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public bool HasNonSmokingRooms {
            get {
                return this.hasNonSmokingRoomsField;
            }
            set {
                this.hasNonSmokingRoomsField = value;
                this.RaisePropertyChanged("HasNonSmokingRooms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public bool HasAirportTransportation {
            get {
                return this.hasAirportTransportationField;
            }
            set {
                this.hasAirportTransportationField = value;
                this.RaisePropertyChanged("HasAirportTransportation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public bool HasAirConditioning {
            get {
                return this.hasAirConditioningField;
            }
            set {
                this.hasAirConditioningField = value;
                this.RaisePropertyChanged("HasAirConditioning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public bool HasClothingIron {
            get {
                return this.hasClothingIronField;
            }
            set {
                this.hasClothingIronField = value;
                this.RaisePropertyChanged("HasClothingIron");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public bool HasWakeUpService {
            get {
                return this.hasWakeUpServiceField;
            }
            set {
                this.hasWakeUpServiceField = value;
                this.RaisePropertyChanged("HasWakeUpService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public bool HasMiniBarInRoom {
            get {
                return this.hasMiniBarInRoomField;
            }
            set {
                this.hasMiniBarInRoomField = value;
                this.RaisePropertyChanged("HasMiniBarInRoom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public bool HasRoomService {
            get {
                return this.hasRoomServiceField;
            }
            set {
                this.hasRoomServiceField = value;
                this.RaisePropertyChanged("HasRoomService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public bool HasHairDryer {
            get {
                return this.hasHairDryerField;
            }
            set {
                this.hasHairDryerField = value;
                this.RaisePropertyChanged("HasHairDryer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public bool HasCarRentDesk {
            get {
                return this.hasCarRentDeskField;
            }
            set {
                this.hasCarRentDeskField = value;
                this.RaisePropertyChanged("HasCarRentDesk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public bool HasFamilyRooms {
            get {
                return this.hasFamilyRoomsField;
            }
            set {
                this.hasFamilyRoomsField = value;
                this.RaisePropertyChanged("HasFamilyRooms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public bool HasKitchen {
            get {
                return this.hasKitchenField;
            }
            set {
                this.hasKitchenField = value;
                this.RaisePropertyChanged("HasKitchen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public bool HasMap {
            get {
                return this.hasMapField;
            }
            set {
                this.hasMapField = value;
                this.RaisePropertyChanged("HasMap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public string PropertyDescription {
            get {
                return this.propertyDescriptionField;
            }
            set {
                this.propertyDescriptionField = value;
                this.RaisePropertyChanged("PropertyDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public double Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
                this.RaisePropertyChanged("Rating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=77)]
        public string GDSChainCode {
            get {
                return this.gDSChainCodeField;
            }
            set {
                this.gDSChainCodeField = value;
                this.RaisePropertyChanged("GDSChainCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=78)]
        public string GDSChaincodeName {
            get {
                return this.gDSChaincodeNameField;
            }
            set {
                this.gDSChaincodeNameField = value;
                this.RaisePropertyChanged("GDSChaincodeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=79)]
        public string DestinationID {
            get {
                return this.destinationIDField;
            }
            set {
                this.destinationIDField = value;
                this.RaisePropertyChanged("DestinationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=80)]
        public string DrivingDirections {
            get {
                return this.drivingDirectionsField;
            }
            set {
                this.drivingDirectionsField = value;
                this.RaisePropertyChanged("DrivingDirections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=81)]
        public string NearbyAttractions {
            get {
                return this.nearbyAttractionsField;
            }
            set {
                this.nearbyAttractionsField = value;
                this.RaisePropertyChanged("NearbyAttractions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=82)]
        public bool AEIsMerchant {
            get {
                return this.aEIsMerchantField;
            }
            set {
                this.aEIsMerchantField = value;
                this.RaisePropertyChanged("AEIsMerchant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=83)]
        public System.DateTime AEModifyDate {
            get {
                return this.aEModifyDateField;
            }
            set {
                this.aEModifyDateField = value;
                this.RaisePropertyChanged("AEModifyDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHotel", WrapperNamespace="http://ws.design.americaneagle.com", IsWrapped=true)]
    public partial class GetHotelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.design.americaneagle.com")]
        public InterviewTest.HotelService.HotelCredentials HotelCredentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.design.americaneagle.com")]
        public InterviewTest.HotelService.ImageOptions ImageOptions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.design.americaneagle.com", Order=0)]
        public int hotelId;
        
        public GetHotelRequest() {
        }
        
        public GetHotelRequest(InterviewTest.HotelService.HotelCredentials HotelCredentials, InterviewTest.HotelService.ImageOptions ImageOptions, int hotelId) {
            this.HotelCredentials = HotelCredentials;
            this.ImageOptions = ImageOptions;
            this.hotelId = hotelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHotelResponse", WrapperNamespace="http://ws.design.americaneagle.com", IsWrapped=true)]
    public partial class GetHotelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.design.americaneagle.com", Order=0)]
        public InterviewTest.HotelService.Hotel GetHotelResult;
        
        public GetHotelResponse() {
        }
        
        public GetHotelResponse(InterviewTest.HotelService.Hotel GetHotelResult) {
            this.GetHotelResult = GetHotelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHotels", WrapperNamespace="http://ws.design.americaneagle.com", IsWrapped=true)]
    public partial class GetHotelsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.design.americaneagle.com")]
        public InterviewTest.HotelService.HotelCredentials HotelCredentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.design.americaneagle.com")]
        public InterviewTest.HotelService.FilterContainer FilterContainer;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.design.americaneagle.com")]
        public InterviewTest.HotelService.ImageOptions ImageOptions;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.design.americaneagle.com")]
        public InterviewTest.HotelService.HotelPagingOptions HotelPagingOptions;
        
        public GetHotelsRequest() {
        }
        
        public GetHotelsRequest(InterviewTest.HotelService.HotelCredentials HotelCredentials, InterviewTest.HotelService.FilterContainer FilterContainer, InterviewTest.HotelService.ImageOptions ImageOptions, InterviewTest.HotelService.HotelPagingOptions HotelPagingOptions) {
            this.HotelCredentials = HotelCredentials;
            this.FilterContainer = FilterContainer;
            this.ImageOptions = ImageOptions;
            this.HotelPagingOptions = HotelPagingOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHotelsResponse", WrapperNamespace="http://ws.design.americaneagle.com", IsWrapped=true)]
    public partial class GetHotelsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws.design.americaneagle.com")]
        public InterviewTest.HotelService.HotelCredentials HotelCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.design.americaneagle.com", Order=0)]
        public InterviewTest.HotelService.Hotel[] GetHotelsResult;
        
        public GetHotelsResponse() {
        }
        
        public GetHotelsResponse(InterviewTest.HotelService.HotelCredentials HotelCredentials, InterviewTest.HotelService.Hotel[] GetHotelsResult) {
            this.HotelCredentials = HotelCredentials;
            this.GetHotelsResult = GetHotelsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelsSoapChannel : InterviewTest.HotelService.HotelsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelsSoapClient : System.ServiceModel.ClientBase<InterviewTest.HotelService.HotelsSoap>, InterviewTest.HotelService.HotelsSoap {
        
        public HotelsSoapClient() {
        }
        
        public HotelsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterviewTest.HotelService.GetHotelResponse InterviewTest.HotelService.HotelsSoap.GetHotel(InterviewTest.HotelService.GetHotelRequest request) {
            return base.Channel.GetHotel(request);
        }
        
        public InterviewTest.HotelService.Hotel GetHotel(InterviewTest.HotelService.HotelCredentials HotelCredentials, InterviewTest.HotelService.ImageOptions ImageOptions, int hotelId) {
            InterviewTest.HotelService.GetHotelRequest inValue = new InterviewTest.HotelService.GetHotelRequest();
            inValue.HotelCredentials = HotelCredentials;
            inValue.ImageOptions = ImageOptions;
            inValue.hotelId = hotelId;
            InterviewTest.HotelService.GetHotelResponse retVal = ((InterviewTest.HotelService.HotelsSoap)(this)).GetHotel(inValue);
            return retVal.GetHotelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterviewTest.HotelService.GetHotelResponse> InterviewTest.HotelService.HotelsSoap.GetHotelAsync(InterviewTest.HotelService.GetHotelRequest request) {
            return base.Channel.GetHotelAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterviewTest.HotelService.GetHotelResponse> GetHotelAsync(InterviewTest.HotelService.HotelCredentials HotelCredentials, InterviewTest.HotelService.ImageOptions ImageOptions, int hotelId) {
            InterviewTest.HotelService.GetHotelRequest inValue = new InterviewTest.HotelService.GetHotelRequest();
            inValue.HotelCredentials = HotelCredentials;
            inValue.ImageOptions = ImageOptions;
            inValue.hotelId = hotelId;
            return ((InterviewTest.HotelService.HotelsSoap)(this)).GetHotelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterviewTest.HotelService.GetHotelsResponse InterviewTest.HotelService.HotelsSoap.GetHotels(InterviewTest.HotelService.GetHotelsRequest request) {
            return base.Channel.GetHotels(request);
        }
        
        public InterviewTest.HotelService.Hotel[] GetHotels(ref InterviewTest.HotelService.HotelCredentials HotelCredentials, InterviewTest.HotelService.FilterContainer FilterContainer, InterviewTest.HotelService.ImageOptions ImageOptions, InterviewTest.HotelService.HotelPagingOptions HotelPagingOptions) {
            InterviewTest.HotelService.GetHotelsRequest inValue = new InterviewTest.HotelService.GetHotelsRequest();
            inValue.HotelCredentials = HotelCredentials;
            inValue.FilterContainer = FilterContainer;
            inValue.ImageOptions = ImageOptions;
            inValue.HotelPagingOptions = HotelPagingOptions;
            InterviewTest.HotelService.GetHotelsResponse retVal = ((InterviewTest.HotelService.HotelsSoap)(this)).GetHotels(inValue);
            HotelCredentials = retVal.HotelCredentials;
            return retVal.GetHotelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterviewTest.HotelService.GetHotelsResponse> InterviewTest.HotelService.HotelsSoap.GetHotelsAsync(InterviewTest.HotelService.GetHotelsRequest request) {
            return base.Channel.GetHotelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterviewTest.HotelService.GetHotelsResponse> GetHotelsAsync(InterviewTest.HotelService.HotelCredentials HotelCredentials, InterviewTest.HotelService.FilterContainer FilterContainer, InterviewTest.HotelService.ImageOptions ImageOptions, InterviewTest.HotelService.HotelPagingOptions HotelPagingOptions) {
            InterviewTest.HotelService.GetHotelsRequest inValue = new InterviewTest.HotelService.GetHotelsRequest();
            inValue.HotelCredentials = HotelCredentials;
            inValue.FilterContainer = FilterContainer;
            inValue.ImageOptions = ImageOptions;
            inValue.HotelPagingOptions = HotelPagingOptions;
            return ((InterviewTest.HotelService.HotelsSoap)(this)).GetHotelsAsync(inValue);
        }
        
        public string SiteScope() {
            return base.Channel.SiteScope();
        }
        
        public System.Threading.Tasks.Task<string> SiteScopeAsync() {
            return base.Channel.SiteScopeAsync();
        }

        internal void GetHotel(HotelsSoapClient hotel, bool v1, int v2)
        {
            throw new NotImplementedException();
        }
    }
}
